### ISSUE TITLE
Complete and up-to-date stubs of WordPress core

### ISSUE THREAD

**Issue by szepeviktor** [skaut/phan-wordpress-stubs#2]
Hello @marekdedic!

https://github.com/php-stubs/wordpress-stubs
This repo contains all stubs, please see `/finder.php` for exceptions.

:)

**Comment by marekdedic** [comment]
Hi,
before creating this package, I saw your repo (or the one you forked, I'm not sure) and I figured it was not complete (e. g. `$args` for `WP_Customize_Color_Control::__construct()` are undocumented). And not only is it incomplete in this regard (obviously it is almost complete with regards to class and function coverage), it is incomplete **by design** - The WordPress handbook [clearly states](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#1-1-parameters-that-are-arrays) that in certain cases, the parameters of functions or hooks are not to be documented. Therefore, mere extraction of stubs from WP source is insufficient.

Anyway, thanks for the suggestion. This package is aimed towards leveraging the type-checking capability of phan (I'm unsure how comparable it is with phpstan/psalm in this regard), so the correctness of the stubs is really important. Unfortunately, I think that means I can't use auto-generated stubs.

**Comment by szepeviktor** [comment]
Thank you for your explanation!

I see! phan read those `@type` array elements, and that is not included in WordPress core's docblocks.

Actually I use another solution: including a data-only class :)
https://github.com/szepeviktor/phpstan-wordpress/blob/master/example/class-wp-nav-menu-args.php
